title: Ramana | AI Engineer
description: Specialist in RAG, Agentic AI, and Knowledge Graphs.
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
google_analytics: # You can add your ID later
show_downloads: false
